### ISSUE TITLE
tgweb 側で fontawesome を供給する必要がある？

### ISSUE THREAD

**Issue by pojiro** [pojiro/teamgenik_pub_samples#11]
tgweb へ切り替え以前は以下のように fontawesome を利用していました。

```
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="../../dist/tailwind.css" rel="stylesheet" />
    <title>kenko</title>
    <!-- fontawesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
      rel="stylesheet"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js"></script>
  </head>
```

---

tgweb のドキュメント, https://github.com/oiax/tgweb#note, によると

> A <link> element that refers to another stylesheet cannot be inserted within the head element.

> The <script> elements are managed by tgweb. 

とのことなので、 tgweb 側で供給する必要がある気がしますがいかがでしょうか？ @kuroda

**Comment by kuroda** [comment]
対応します。少々お待ちください。

**Comment by pojiro** [comment]
ざっと見ですが、 fontawesome は 

- kit, https://fontawesome.com/docs/web/setup/use-kit#what-s-a-kit

を推奨しているようなので方針を検討する必要があるかもです。

see. https://fontawesome.com/v5/docs/web/use-with/wordpress/install-manually#cdn-vs-kit

私が上記で試した方法は正攻法ではない可能性があります。

**Comment by kuroda** [comment]
Font Awesome Kit は Web サービスなので、アカウントを作って連携する必要がありますね。

できれば、そういう複雑なことを Teamgenik のユーザーにやらせたくないです。

Font Awesome の代わりに Google Fonts が提供しているアイコンを使おうかと思案中です。

https://fonts.google.com/icons

**Comment by kuroda** [comment]
tgweb 0.1.11 で Google Material Symbols に対応しました。

**Comment by pojiro** [comment]
Closed by #19
