### ISSUE TITLE
`npx tgweb-init [site name]` が作成する dist ディレクトリ配下に .gitignore を含むほうがいいかも

### ISSUE THREAD

**Issue by pojiro** [pojiro/teamgenik_pub_samples#20]
dist 配下のファイルは自動生成され VCS の管理対象外と考えられるため、npx コマンドで dist ディレクトリを生成するタイミングで .gitignore を追加してしまうのも良いかもしれません。

**Comment by kuroda** [comment]
`tgweb 0.1.12` で対応しました。

作業ディレクトリ直下に次のような `.gitignore` を作るようにしました:

```
/node_modules
/dist
/sites/*/dist
```

**Comment by pojiro** [comment]
Closed by https://github.com/oiax/tgweb/commit/f864205260db6e31ff9b6b359f71c86e64e39ab5
