### ISSUE TITLE
style 属性は使用できません

### ISSUE THREAD

**Issue by kuroda** [pojiro/teamgenik_pub_samples#3]
伝え忘れたかと思いますが、Teamgenik では `style` 属性は使えません。

```html
  <div
    class="h-full border border-white text-gray-600"
    style="
      background: linear-gradient(to right, white, transparent),
        url('../images/not-pot-j8Pfv4nnuyE-unsplash.jpg');
    "
  >
```

できるかどうかわかりませんが、この辺りを参考にして Tailwiind CSS のクラスのみで画像付きのグラデーション背景にトライしてください。

* https://tailwindcss.com/docs/gradient-color-stops
* https://tailwindcss.com/docs/background-image#arbitrary-values

**Comment by kuroda** [comment]
実質的に `src` 属性を書いているのと同じみたいですが、次のクラスで同じ効果を得られました。

```
bg-[linear-gradient(to_right,_white,_transparent),url('../images/not-pot-j8Pfv4nnuyE-unsplash.jpg')]
```

**Comment by pojiro** [comment]
@kuroda 

上記、報告漏れでした。申し訳ありません。

いただいた修正を #4 として main に取り込みました。
※取り込むにあたり、`url()`内のパスを微修正しました。その理由は #4 に記載しておりますのでご確認下さい。

**Comment by kuroda** [comment]
この動画（10分）で説明されているテクニックを用いると、もっとエレガントに書けそうです。

https://www.youtube.com/watch?v=5UPdRF5xpVM

**Comment by pojiro** [comment]
教えていただきありがとうございます！ #5 で書き換えを試してみました！

**Comment by pojiro** [comment]
Closed by #5
