### ISSUE TITLE
segment のドキュメントにも `There is only one top-level element.` のような記述があったほうがよいかも？

### ISSUE THREAD

**Issue by pojiro** [pojiro/teamgenik_pub_samples#31]
@kuroda 

segment は top-level element が複数ある場合に第一要素のみをレンダリングし、それ以降はレンダリングしませんでした。
※ tgweb 0.2.2 で確認しています。

これは layout のドキュメントにある `There is only one top-level element.` のような仕様が要求しているからと思います。
なので、その旨のドキュメント、複数トップ要素がある場合のエラー出力等を検討してみるのはいかがでしょう？

**Comment by kuroda** [comment]
ご報告ありがとうございます。

テンプレートのトップレベル要素が1個だけという制限は撤廃予定です。次の v.0.2.3 で対応します。

**Comment by kuroda** [comment]
v0.2.3 をリリースしました。セグメントもコンポーネントも複数のトップレベル要素を持てるようになっています。

**Comment by pojiro** [comment]
v0.2.4 で動作確認できたのでクローズします。
ref. #35
