### ISSUE TITLE
tgweb v0.2.3 以降 layout がレンダリングされない

### ISSUE THREAD

**Issue by pojiro** [pojiro/teamgenik_pub_samples#36]
@kuroda 

title の現象を v0.2.3, v0.2.4 で確認しています。ご確認をお願いいたします。

以下、再現方法

```
npm i
VERBOSE=1 npx tgweb-server astronomy_club
```

default.html の <tg-content> しかレンダリングされていないようです。（hero.html, footer.htmlが表示されず、body の class もない）

**Comment by kuroda** [comment]
修正しました。`v0.2.5` を使用してください。

`site.yml` に書かれた `layout` が読み込まれなくなっていました。

**Comment by pojiro** [comment]
動作確認できました！ Closed by #37
