### ISSUE TITLE
tgweb v0.2.6 で articles の front matter の `data-xxx` が効かない

### ISSUE THREAD

**Issue by pojiro** [pojiro/teamgenik_pub_samples#42]
@kuroda タイトルの現象を確認しました。

再現方法

```
# main ブランチで
VERBOSE=1 npx tgweb-server arakawa
```

以下、赤枠キャプチャ内はグランド名が入るはずですが入りません。

![image](https://user-images.githubusercontent.com/4096956/226497515-548ede57-4ba4-4793-b727-cfda59632342.png)

ref. https://github.com/pojiro/teamgenik_pub_samples/blob/b99db333fc046131d0cdb1ae7253676f15bb3ca9/sites/arakawa/src/articles/grounds/arakawa-boys.html

**Comment by kuroda** [comment]
@pojiro ありがとうございます。

`v0.2.7` で修正しました。

**Comment by pojiro** [comment]
動作を確認できました！ Closed by #43
