### ISSUE TITLE
天文部: フィードバック

### ISSUE THREAD

**Issue by kuroda** [pojiro/teamgenik_pub_samples#48]
`articles/quizzes/quiz-01.html` 等に含まれる3個の `<button>` 要素はビジュアルデザインが共通しています。コンポーネントとして抜き出してください。コンポーネントの使用例としてユーザーに見せたいです。

**Comment by pojiro** [comment]
ご指摘ありがとうございます。対応いたします！

**Comment by pojiro** [comment]
@kuroda 修正 PR #51 を作成しました。ご確認お願いいたします。

※tgweb は 0.2.11 アップデートしています。
