### ISSUE TITLE
ディレクトリ構造の変更

### ISSUE THREAD

**Issue by kuroda** [pojiro/teamgenik_pub_samples#6]
今後、kenko の他にも複数のウェブサイトを tgweb 化していくことを考えると、[Managing multiple websites](https://github.com/oiax/tgweb#managing-multiple-websites) で説明されているディレクトリ構造に変えた方がよいと思われます。

```bash
mkdir -p sites/popup_store
mv src dist tailwind* sites/popup_store/
```

この構成に変えたら、サーバーを起動するコマンドはこうなります。

```bash
npx tgweb-server popup_store
```

新しいウェブサイトの骨格を作るコマンドはこれです。

```bash
npx tgweb-init new_site
```

**Comment by pojiro** [comment]
承知しました！ 変更して進めるようにいたします。
