### ISSUE TITLE
npx tgweb-server が default.html の変更で Rebuild は起きるが、default.html の変更が反映しない

### ISSUE THREAD

**Issue by pojiro** [pojiro/teamgenik_pub_samples#8]
### 再現方法

`npx tgweb-server popup_store` でサーバ起動中に、

https://github.com/pojiro/teamgenik_pub_samples/blob/f3128bdb0ea9646fdf2958cfb5874d29d0b5ef4b/sites/popup_store/src/layouts/default.html#L2

の class を変更したり、 tag 挿入をしても変更が反映されませんでした。

@kuroda この動作は意図（仕様）通りか、ご確認をお願いできますでしょうか？

**Comment by kuroda** [comment]
tgweb の 0.1.11 では直っているはずです。ご確認ください。

**Comment by pojiro** [comment]
Closed by #19
