### ISSUE TITLE
layout で front matter を使いたい（？

### ISSUE THREAD

**Issue by pojiro** [pojiro/teamgenik_pub_samples#9]
index.html で当てている以下のようなメタタグは layout 共通で使用できると嬉しい気がします。

https://github.com/pojiro/teamgenik_pub_samples/blob/f3128bdb0ea9646fdf2958cfb5874d29d0b5ef4b/sites/popup_store/src/pages/index.html#L3-L4

@kuroda どうでしょう？

**Comment by kuroda** [comment]
とりあえず、`site.yml` で指定して、サイト全体に効かせてください。

将来的には、layout レベルで指定しても効くようにします。

**Comment by pojiro** [comment]
#13 で site.yml を使用するように変更しました。

**Comment by kuroda** [comment]
`tgweb 0.1.11` で対応しました。

**Comment by pojiro** [comment]
https://github.com/pojiro/teamgenik_pub_samples/tree/test-layout-front-matter の 118ce06cfab1cd3adf7080a9c29851f5fab4f370 で試してみましたが、 head にタグが挿入されませんでした。ご確認お願いいたします。

**Comment by kuroda** [comment]
`tgweb 0.1.12` で修正しました。

再確認をお願いいたします。

**Comment by pojiro** [comment]
機能の動作が確認できました！

This feature is released in https://github.com/oiax/tgweb/commit/f864205260db6e31ff9b6b359f71c86e64e39ab5
